name: 📺 每日追剧提醒

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: 发送微信推送
        env:
          SENDKEY: ${{ secrets.SENDKEY }}
        run: node .github/workflows/push.js
