name: 📺 每日追剧提醒

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: 发送微信推送
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: node .github/workflows/push.js
